### ISSUE TITLE
Float64Column.Values() panic again

### ISSUE THREAD

**Issue by longwallstreet** [sglyon/feather#2]
Hi, sglyon
   Last year,  I find a problem, when nNull > 0, Float64Colume.Values() panic in column.go. You solved this problem at the time, now I have the same problem again. Can you help debug it? 
test data is ic.zip, please unzip to ic.csv,  2 columns, 28358 rows of data
[ic.zip](https://github.com/sglyon/feather/files/3177529/ic.zip)

step 1: use python convert to ic.feather

```python
import feather
import pandas as pd
df = pd.read_csv('ic.csv', dtype={'LastPrice':float,'Turnover':float})  
feather.write_dataframe(df, 'ic.feather')
```

step 2: use golang read ic.feather

```go
package main

import (
	"fmt"

	"github.com/sglyon/feather"
)

func main() {
	src, err := feather.Read("ic.feather")
	if err != nil {
		panic(err)
	}
	lastpxCol := src.Columns[0].(*feather.Float64Column)
	lastpxVals, _ := lastpxCol.Values()
	turnoverCol := src.Columns[1].(*feather.Float64Column)
	turnoverVals, _ := turnoverCol.Values()

	if len(lastpxVals) != len(turnoverVals) {
		panic("missing len")
	}

	for i := 0; i < len(lastpxVals); i++ {
		fmt.Printf("%f, %f\n", lastpxVals[i], turnoverVals[i])
	}
}
```

result:
turnoverCol.Values() crash.

**Comment by sglyon** [comment]
Hey @longwallstreet thanks for posting again -- I have pushed a fix that I believe fixes this problem. Can you please confirm?

Thanks

**Comment by longwallstreet** [comment]
Hi @sglyon  I tested it and this probllem has been perfectly fixed. Thank you very much.

**Comment by sglyon** [comment]
Excellent, thank you for following up
